#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
set -e

pnpm run format

# Add files that were already staged and modified by the formatter to staging
# Dont add files that were deleted
git diff --name-status --cached | while read status file; do
  if [ "$status" != "D" ]; then
    git add "$file"
  fi
done